"""共享查询模板：dest -> 自然语言查询。所有 provider 使用同一份。"""
from __future__ import annotations

QUERY_BY_DEST: dict[str, str] = {
    "url": "citibank singapore all promo fixed deposit",
    "cimb_sgd_url": "cimb singapore sgd fixed deposit rates",
    "cimb_url": "cimb singapore foreign currency fixed deposit account",
    "hl_url": "hong leong bank singapore fixed deposit promotion",
    "hlf_url": "hong leong finance fixed deposit promotion singapore",
    "hsbc_url": "hsbc singapore time deposit account",
    "icbc_url": "icbc singapore fixed deposit promotion",
    "ocbc_url": "ocbc singapore fixed deposit account promotion",
    "rhb_url": "rhb singapore fixed deposit campaign",
    "rhb_fcy_url": "rhb singapore foreign currency fixed deposit campaign",
    "sif_url": "singfinance singapore fixed deposit",
    "scb_url": "standard chartered singapore dollar time deposit",
    "scb_fcy_url": "standard chartered singapore foreign currency time deposit",
    "sbi_url": "sbi singapore sgd fixed deposit promotions",
    "sbi_usd_url": "sbi singapore usd fixed deposit promotions",
    "uob_url": "uob singapore fixed deposit promotion",
    "boc_url": "bank of china singapore deposit promotion fixed",
    "citi_board_url": "citibank singapore fixed deposit account board rates",
    "dbs_board_url": "dbs singapore dollar fixed deposit rate online",
    "hl_board_url": "hong leong bank singapore fixed deposit rate",
    "hlf_board_url": "hong leong finance fixed deposits singapore rates",
    "hsbc_board_url": "hsbc singapore dollar deposits interest rates",
    "icbc_board_url": "icbc singapore sgd fixed deposit rates board",
    "icbc_fcy_board_url": "icbc singapore foreign currency fixed deposit rates",
    "maybank_board_url": "maybank singapore deposit interest rates",
    "ocbc_board_url": "ocbc sgd fixed deposit interest rates",
    "rhb_board_pdf_url": "rhb singapore deposit rates pdf",
    "sif_board_url": "singfinance singapore deposit rates",
    "scb_board_url": "standard chartered singapore sgd time deposit interest rates",
    "sbi_board_url": "sbi singapore interest rates deposit",
    "uob_board_url": "uob singapore dollar time fixed deposit rates",
    "bea_sgd_board_api_url": "bea singapore fixed deposit rate enquiry api",
    "bea_fcy_board_api_url": "bea singapore foreign currency fixed deposit rate api",
    "boc_board_url": "bank of china singapore deposit rates board",
    "bea_sgd_promo_url": "bank of east asia singapore deposit promotion",
    "bea_fcy_promo_url": "bea singapore foreign currency deposit promotion",
    "maybank_sgd_promo_url": "maybank singapore sgd time deposit promotion",
    "hsbc_fcy_promo_url": "hsbc singapore foreign currency time deposit rates pdf",
    "dbs_fcy_board_api_url": "dbs singapore foreign currency fixed deposit rates api",
    "ocbc_fcy_board_url": "ocbc daily price foreign currency fixed deposit rates",
    "uob_fcy_board_url": "uob foreign currency fixed deposit rates singapore",
    "hl_fcy_board_url": "hong leong bank foreign currency fixed deposit singapore",
    "hsbc_fcy_board_url": "hsbc foreign currency time deposits rates singapore",
    "maybank_fcy_board_url": "maybank singapore foreign currency deposit rates",
    "scb_fcy_board_url": "standard chartered foreign currency interest rates singapore",
    "sbi_fcy_board_url": "sbi singapore interest rates foreign currency",
    "rhb_fcy_board_pdf_url": "rhb singapore foreign currency deposit rates pdf",
}
